type snowflake;
type collection('k, 'v);
type message;
type guild;
type client;
type client_user;
type channel;
type user;
type voice_conn;
type voice_boradcast;
type dmChannel;
type groupDMChannel;
type textChannel;
type voiceChannel;